### ISSUE TITLE
Texture clipping issue

### ISSUE THREAD

**Issue by MrKumaPants** [amethyst/amethyst-starter-2d#12]
![image](https://user-images.githubusercontent.com/39394314/71652110-8c885080-2ce8-11ea-8142-ac1478dc9b6a.png)

**Comment by 0x6273** [comment]
The sprites display correctly on my system (Linux, Vulkan renderer). It looks like the sprites are off by a pixel on the texture sheet, so maybe there is an off-by-one bug somewhere in Amethyst that only triggers on windows?

**Comment by 0x6273** [comment]
Can you include a bit more information about your system and your setup? A user on discord tried to replicate this on windows on both stable and nightly rustc, and it rendered correctly for them.

**Comment by MrKumaPants** [comment]
> Can you include a bit more information about your system and your setup? A user on discord tried to replicate this on windows on both stable and nightly rustc, and it rendered correctly for them.

I'm guessing it's a hidpi issue. 

Windows 10
Nvidia 2080
4k monitor with zoom set to 125%
