### ISSUE TITLE
Update to v0.14.0

### ISSUE THREAD

**Issue by MalteT** [amethyst/amethyst-starter-2d#13]
This example is slightly out of date as it is based on v0.13.
New users might be frustrated by the changes needed to work with v0.14.

I could assemble a PR, if there's no reason to stay at v0.13, i.e. some reference that states that this should work with amethyst v0.13.

#12 might be related to https://github.com/amethyst/amethyst/pull/2103 which is contained in v0.14.

**Comment by SET001** [comment]
Confirming that. I'm a new user that is being frustrated by the changes needed to work with v0.14
so far I was not able to fix it myself (being first-day amethyst user) and had to switch to 0.13

**Comment by mmahandev** [comment]
v0.15.0 is out so that would be best now

**Comment by happenslol** [comment]
Fixed in #14, sorry for the delay.
