### ISSUE TITLE
Windows 10: Starter project crashes a few seconds after launching

### ISSUE THREAD

**Issue by datalus** [amethyst/amethyst-starter-2d#2]
I receive this error when running the starter project:

error: process didn't exit successfully: `target\debug\amethyst-starter-2d.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

I have a bit of a weird setup, rendy maybe selecting my GTX 1070 instead of the GPU I use for display: an RX Vega 64. 

A lot of the gfx_backend_vulkan INFO logs are spitting out features from the nvidia driver. 

This is using: rustc 1.36.0 (a53f9df32 2019-07-03) msvc

**Comment by Dispersia** [comment]
This is due to vulkan validation layers: (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1035) which has been fixed. Fusha in discord posted in the FAQ:

> The latest version (1.1.108) of the Vulkan SDK currently has a bug which causes a segfault in the validation layers when run with Amethyst. This has already been patched (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1035) in the Validation Layers git, however this has not been in a release yet. For now to solve this you can do any one of the following: 
> 
> 1. Downgrade your Vulkan SDK to 1.1.106
> 2. Always run in --release mode, which will cause the validation layers to not be loaded
> 3. Build the Vulkan SDK/Validation Layers from source for the latest fix

 Unfortunately, nothing this repo can fix

**Comment by happenslol** [comment]
Closing since this problem originates in vulkan, as @Dispersia said.

**Comment by Sorrien** [comment]
Installing the latest Vulkan (Vulkan 1.1.114.0 at the moment) fixed this for me.

**Comment by Dispersia** [comment]
Also note that 114 seems to also cause issues for some windows users that's separate from this original issue, but it does get you past this issue (and hopefully you won't have the new one)
